AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Application_Layer Template
Globals:
  Function:
    Timeout: 120
    MemorySize: 512
    Handler: handler.main
    Runtime: python3.10
    VpcConfig:
      SecurityGroupIds:
      - Fn::ImportValue: SecurityLayer-SecurityGroupLambda
      SubnetIds:
      - Fn::ImportValue: NetworkLayer-PrivateSubnetA
      - Fn::ImportValue: NetworkLayer-PrivateSubnetB
    Layers:
    - Ref: MyLayer
Resources:
  SampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://dev-yuki-bucket-test/196f993f21d445423a5e0989119219d3
      Role:
        Fn::ImportValue: IamLayer-LambdaRoleArn
      Policies:
      - Fn::ImportValue: IamLayer-LambdaRole
  MyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: MyLayer
      Description: My custom runtime layer
      ContentUri: s3://dev-yuki-bucket-test/96ab27340616e3d76dd722ec0891aad4
      CompatibleRuntimes:
      - python3.10
      LicenseInfo: MIT
      RetentionPolicy: Retain
