AWSTemplateFormatVersion: 2010-09-09
Description: EC2_Layer Template
Resources:
  DevEC2:
    Type: AWS::EC2::Instance
    Properties:
      NetworkInterfaces:
      - SubnetId:
          Fn::ImportValue: NetworkLayer-PublicSubnetA
        GroupSet:
        - Fn::ImportValue: SecurityLayer-SecurityGroupEC2
        DeviceIndex: 0
      LaunchTemplate:
        LaunchTemplateId:
          Fn::ImportValue: EC2TemplateLayer-LaunchTemplate
        Version: 1
      UserData:
        Fn::Base64: "#!/bin/bash\n\ngroupadd honoka\nuseradd honoka -g honoka\ngpasswd\
          \ -a honoka wheel\necho sk4869sk | passwd --stdin honoka\ncp -frv /home/ec2-user/.ssh\
          \ /home/honoka/\nchown -R honoka:honoka /home/honoka/.ssh\nchmod 700 /home/honoka/.ssh\n\
          chmod 600 /home/honoka/.ssh/*\nhostnamectl set-hostname devEC2\nlocalectl\
          \ set-locale LANG=ja_JP.UTF-8\ntimedatectl set-timezone Asia/Tokyo\ndnf\
          \ update -y\ndnf -y install epel-release \ndnf -y install elrepo-release\n\
          dnf -y install https://rpms.remirepo.net/enterprise/remi-release-8.rpm\n\
          dnf -y install git vim curl wget podman podman-docker\ncurl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname\
          \ -s)-$(uname -m) -o /usr/local/bin/docker-compose\nchmod 755 /usr/local/bin/docker-compose\n\
          cp -p /etc/selinux/config /etc/selinux/config.org~\nsed -i 's/\\(^SELINUX=\\\
          )enforcing/\\1disabled/' /etc/selinux/config\nshutdown -r now\n"
      Tags:
      - Key: Name
        Value: DevEC2
  EC2EIPAttouch:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId:
        Fn::ImportValue: NetworkLayer-EIP
      InstanceId:
        Ref: DevEC2
