AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 120
    MemorySize: 512
    Handler: handler.main
    Runtime: python3.10
    Role: !GetAtt LambdaExecutionRole.Arn # Roleを紐付け
    VpcConfig:
      SecurityGroupIds:
        - !Ref WebSecurityGroup # WebSecurityGroupと紐付け
      SubnetIds:
        - !Ref PrivateSubNet01b #Subnet(private)と紐付け
        - !Ref PrivateSubNet02b #Subnet(private)と紐付け
    Layers:
      - !Ref MyLayer

Resources:
  IamRole:
    Type: AWS::Include
    Properties:
      Location: ./iam/iam_role.yaml

  Vpc:
    Type: AWS::Include
    Properties:
      Location: ./net/vpc.yaml

  Subnets:
    Type: AWS::Include
    Properties:
      Location: ./net/subnets.yaml

  RouteTables:
    Type: AWS::Include
    Properties:
      Location: ./net/route_tables.yaml

  InternetGateway:
    Type: AWS::Include
    Properties:
      Location: ./net/internet_gateway.yaml

  ElasticIP:
    Type: AWS::Include
    Properties:
      Location: ./net/elastic_ip.yaml

  NatGateway:
    Type: AWS::Include
    Properties:
      Location: ./net/nat_gateway.yaml

  SecurityGroup:
    Type: AWS::Include
    Properties:
      Location: ./net/web_security_group.yaml

  Lambda:
    Type: AWS::Include
    Properties:
      Location: ./net/api-gateway/lambda.yaml

  Layer:
    Type: AWS::Include
    Properties:
      Location: ./api-gateway/layer.yaml

  ApiGateway:
    Type: AWS::Include
    Properties:
      Location: ./api-gateway/api-gateway.yaml
