AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Application_Layer Template
Globals:
  Api:
    OpenApiVersion: 3.0.2
  Function:
    Timeout: 120
    MemorySize: 512
    Handler: handler.main
    Runtime: python3.11
    VpcConfig:
      SecurityGroupIds:
      - Fn::ImportValue: SecurityLayer-SecurityGroupLambda
      SubnetIds:
      - Fn::ImportValue: NetworkLayer-PrivateSubnetA
      - Fn::ImportValue: NetworkLayer-PrivateSubnetB
    Layers:
    - Ref: MyLayer
Resources:
  ApiGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::ImportValue: IamLayer-LambdaRoleArn
  RestApi:
    Type: AWS::Serverless::Api
    DependsOn: ApiGatewayAccount
    Properties:
      StageName: dev
      OpenApiVersion: 3.0.2
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: s3://dev-yuki-bucket-test/4518602f37ac8989da2601cc0cfe8b3b
      EndpointConfiguration: REGIONAL
      MethodSettings:
      - ResourcePath: /*
        HttpMethod: '*'
        LoggingLevel: INFO
        DataTraceEnabled: true
      AccessLogSetting:
        DestinationArn:
          Fn::GetAtt:
          - MyLogGroup
          - Arn
        Format: $context.extendedRequestId $context.identity.sourceIp $context.identity.caller
          $context.identity.user [$context.requestTime] "$context.httpMethod $context.resourcePath
          $context.protocol" $context.status $context.responseLength $context.requestId
  MyLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
        - '-'
        - - Ref: RestApi
          - access-logs
  SampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: SampleFunction
      FunctionName: sample-function
      Role:
        Fn::ImportValue: IamLayer-LambdaRoleArn
      CodeUri: s3://dev-yuki-bucket-test/83d66829667b59a74424c37ec5ce62b8
      Events:
        Post:
          Type: Api
          Properties:
            RestApiId:
              Ref: RestApi
            Path: /sample
            Method: POST
        Get:
          Type: Api
          Properties:
            RestApiId:
              Ref: RestApi
            Path: /sample
            Method: GET
      Tags:
        STAGE: dev
  MyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: MyLayer
      Description: My custom runtime layer
      ContentUri: s3://dev-yuki-bucket-test/464680bf65d7856d660621707053e4d4
      CompatibleRuntimes:
      - python3.11
      LicenseInfo: MIT
      RetentionPolicy: Retain
