AWSTemplateFormatVersion: 2010-09-09
Description: EC2_Layer Template
Resources:
  DevEC2:
    Type: AWS::EC2::Instance
    Properties:
      NetworkInterfaces:
      - SubnetId:
          Fn::ImportValue: NetworkLayer-PublicSubnetA
        GroupSet:
        - Fn::ImportValue: SecurityLayer-SecurityGroupEC2
        DeviceIndex: 0
      LaunchTemplate:
        LaunchTemplateId:
          Fn::ImportValue: EC2TemplateLayer-LaunchTemplate
        Version: 1
      UserData:
        Fn::Base64: "#!/bin/bash\n\ngroupadd honoka\nuseradd honoka -g honoka\ngpasswd\
          \ -a honoka wheel\necho sk4869sk | passwd --stdin honoka\ncp -frv /home/ec2-user/.ssh\
          \ /home/honoka/\nchown -R honoka:honoka /home/honoka/.ssh\nchmod 700 /home/honoka/.ssh\n\
          chmod 600 /home/honoka/.ssh/*\nhostnamectl set-hostname devEC2\nlocalectl\
          \ set-locale LANG=ja_JP.UTF-8\ntimedatectl set-timezone Asia/Tokyo\ncp -p\
          \ /etc/selinux/config /etc/selinux/config.org~\nsed -i 's/\\(^SELINUX=\\\
          )enforcing/\\1disabled/' /etc/selinux/config\ndnf update -y\ndnf -y install\
          \ epel-release \ndnf -y install elrepo-release\ndnf -y install https://rpms.remirepo.net/enterprise/remi-release-8.rpm\n\
          dnf -y install git vim curl wget podman podman-docker zip unzip p7zip\n\
          curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname\
          \ -s)-$(uname -m) -o /usr/local/bin/docker-compose\nchmod 755 /usr/local/bin/docker-compose\n\
          wget -c https://github.com/ogham/exa/releases/download/v0.10.1/exa-linux-x86_64-v0.10.1.zip\n\
          unzip exa-linux-x86_64-v0.10.1.zip\ncp ./bin/exa /usr/local/bin/\ncurl -L\
          \ \"https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip\" -o \"awscliv2.zip\"\
          \nunzip awscliv2.zip\n./aws/install\nrm -dev ./awscliv2.zip ./aws\ncurl\
          \ -OL https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip\n\
          unzip aws-sam-cli-linux-x86_64.zip -d sam-installation\n./sam-installation/install\n\
          sam --version\nshutdown -r now\n"
      Tags:
      - Key: Name
        Value: DevEC2
  EC2EIPAttouch:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId:
        Fn::ImportValue: NetworkLayer-EIP
      InstanceId:
        Ref: DevEC2
