AWSTemplateFormatVersion: 2010-09-09
Description: Security_Layer Template
Resources:
  SecurityGroupLambda:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SecurityGroupLambda
      GroupName: SecurityGroupLambda
      Tags:
      - Key: Name
        Value: SecurityGroupLambda
      VpcId:
        Fn::ImportValue: NetworkLayer-VPC
  SecurityGroupEC2:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SecurityGroupEC2
      GroupName: SecurityGroupEC2
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: udp
        FromPort: 4500
        ToPort: 4500
        CidrIp: 0.0.0.0/0
      - IpProtocol: udp
        FromPort: 500
        ToPort: 500
        CidrIp: 0.0.0.0/0
      Tags:
      - Key: Name
        Value: SecurityGroupEC2
      VpcId:
        Fn::ImportValue: NetworkLayer-VPC
Outputs:
  SecurityGroupEC2:
    Value:
      Ref: SecurityGroupEC2
    Export:
      Name: SecurityLayer-SecurityGroupEC2
  SecurityGroupLambda:
    Value:
      Ref: SecurityGroupLambda
    Export:
      Name: SecurityLayer-SecurityGroupLambda
