AWSTemplateFormatVersion: 2010-09-09
Description: EC2_Template_Layer Template

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
  AmiID:
    Description: Please input Ami ID
    Type: AWS::EC2::Image::Id
    Default: ami-078296f82eb463377
  KeyPair:
    Description: Please input KeyPair name
    Type: AWS::EC2::KeyPair::KeyName
    Default: YUKI_ONO

Resources:
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        InstanceType: !Ref InstanceType
        # NetworkInterfaces:
        #   - DeviceIndex: 0
        #     SubnetId: !ImportValue NetworkLayer-PublicSubnetA
        # SecurityGroupIds:
        #  - !ImportValue SecurityLayer-SecurityGroupEC2
        BlockDeviceMappings:
          - DeviceName: /dev/sda1
            Ebs:
              VolumeType: gp3
              VolumeSize: 30
              DeleteOnTermination: false
              Encrypted: 'true'
              Iops: 3000
              Throughput: 250
        ImageId: !Ref AmiID
        KeyName: !Ref KeyPair

Outputs:
  LaunchTemplate:
    Value: !Ref LaunchTemplate
    Export:
      Name: EC2TemplateLayer-LaunchTemplate




      /dev/xvdb: UUID="c91b16e7-fda6-4ff8-8d1d-1e8233517978" BLOCK_SIZE="512" TYPE="xfs"